# Generated by Django 4.1 on 2024-06-06 02:23

from django.db import migrations, models
import endereco.models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0002_endereco2_alter_endereco_cep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', endereco.models.EnderecoField(verbose_name='Endereço')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Endereço 2',
                'verbose_name_plural': 'Endereços 2',
            },
        ),
        migrations.DeleteModel(
            name='Endereco2',
        ),
    ]
