# Generated by Django 5.0.6 on 2024-06-09 17:06

import endereco.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0003_endereco3_delete_endereco2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endereco3',
            options={'verbose_name': 'Endereço 3', 'verbose_name_plural': 'Endereços 3'},
        ),
        migrations.AddField(
            model_name='endereco',
            name='endereco',
            field=endereco.models.EnderecoField(default='', verbose_name='Endereço Interno'),
        ),
    ]
