# Generated by Django 5.0.6 on 2024-06-09 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0004_alter_endereco3_options_endereco_endereco'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Endereco3',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='endereco',
        ),
    ]
