# Generated by Django 5.0.6 on 2024-06-11 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pessoa.pessoa')),
                ('cpf', models.CharField(max_length=20, null=True, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=100, null=True, verbose_name='Nome')),
                ('certificacao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Certificação')),
            ],
            options={
                'verbose_name': 'Pessoa Física',
                'verbose_name_plural': 'Pessoas Físicas',
            },
            bases=('pessoa.pessoa',),
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pessoa.pessoa')),
                ('cnpj', models.CharField(max_length=30, unique=True, verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('atividade', models.CharField(max_length=100, verbose_name='Atividade')),
                ('ie', models.CharField(max_length=30, verbose_name='IE')),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='endereco.endereco')),
                ('proprietario', models.ManyToManyField(related_name='Proprietario', to='pessoa.pessoafisica')),
                ('responsavel_tecnico', models.ManyToManyField(related_name='ResponsavelTecnico', to='pessoa.pessoafisica')),
            ],
            options={
                'verbose_name': 'Pessoa Jurídica',
                'verbose_name_plural': 'Pessoas Jurídicas',
            },
            bases=('pessoa.pessoa',),
        ),
    ]
