# Generated by Django 4.1 on 2024-05-29 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0002_delete_veiculo'),
        ('pessoa', '0002_pessoa_pessoafisica_pessoajuridica_delete_endereco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='proprietario',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='responsavel_tecnico',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.DeleteModel(
            name='PessoaFisica',
        ),
        migrations.DeleteModel(
            name='PessoaJuridica',
        ),
    ]
