# Generated by Django 4.1 on 2024-05-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoafisica',
            name='cpf',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='cnpj',
            field=models.CharField(max_length=30, unique=True, verbose_name='CNPJ'),
        ),
    ]
