# Generated by Django 4.1 on 2024-06-03 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0002_endereco2_alter_endereco_cep'),
        ('pessoa', '0005_alter_pessoafisica_cpf_alter_pessoajuridica_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoajuridica',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='endereco.endereco'),
        ),
    ]
