# Generated by Django 5.0.6 on 2024-06-11 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(default='', max_length=30, verbose_name='Marca')),
                ('modelo', models.CharField(default='', max_length=30, verbose_name='Modelo')),
                ('ano', models.CharField(default='', max_length=15, verbose_name='Ano')),
                ('chassi', models.CharField(default='', max_length=30, verbose_name='Chassi')),
                ('crlv', models.CharField(default='', max_length=30, verbose_name='Crlv')),
                ('renavam', models.CharField(default='', max_length=30, verbose_name='Renavam')),
                ('placa', models.CharField(default='', max_length=30, verbose_name='Placa')),
                ('atividade', models.CharField(default='', max_length=100, verbose_name='Atividade')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Titular', to='pessoa.pessoa')),
                ('proprietario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Proprietario_Veiculo', to='pessoa.pessoafisica', verbose_name='Proprietário do Veículo')),
                ('responsavel_tecnico', models.ManyToManyField(null=True, related_name='Responsavel_Tecnico_Veiculo', to='pessoa.pessoafisica')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
            },
        ),
    ]
