# Generated by Django 4.1 on 2024-05-29 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Veiculo',
        ),
    ]
