# Generated by Django 4.1 on 2024-05-29 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0004_initial'),
        ('veiculo', '0002_delete_veiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.pessoa')),
                ('proprietario', models.ManyToManyField(related_name='Proprietario_Veiculo', to='pessoa.pessoafisica')),
                ('responsavel_tecnico', models.ManyToManyField(related_name='Responsavel_Tecnico_Veiculo', to='pessoa.pessoafisica')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
            },
        ),
    ]
