# Generated by Django 4.1 on 2024-06-03 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0006_alter_pessoajuridica_endereco'),
        ('veiculo', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='ano',
            field=models.CharField(default='', max_length=15, verbose_name='Ano'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='atividade',
            field=models.CharField(default='', max_length=100, verbose_name='Atividade'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='chassi',
            field=models.CharField(default='', max_length=30, verbose_name='Chassi'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='crlv',
            field=models.CharField(default='', max_length=30, verbose_name='Crlv'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='marca',
            field=models.CharField(default='', max_length=30, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(default='', max_length=30, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(default='', max_length=30, verbose_name='Placa'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='renavam',
            field=models.CharField(default='', max_length=30, verbose_name='Renavam'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Titular', to='pessoa.pessoa'),
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='proprietario',
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='responsavel_tecnico',
            field=models.ManyToManyField(null=True, related_name='Responsavel_Tecnico_Veiculo', to='pessoa.pessoafisica'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='proprietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Proprietario_Veiculo', to='pessoa.pessoafisica', verbose_name='Proprietário do Veículo'),
        ),
    ]
